# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 20:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20160328_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2016, 3, 28, 20, 13, 30, 286044, tzinfo=utc)),
        ),
    ]
